# Generated by Django 5.0.6 on 2024-06-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='author',
            new_name='author_id',
        ),
    ]
