# Generated by Django 5.0.6 on 2024-06-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_drink_downvotes_drink_upvotes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
